<?php

namespace App\Models;
use App\Observers\FangAttrObserver;

class Fangattr extends Base
{
    protected $appends=['actionBtn'];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(FangAttrObserver::class);
    }
    public function getactionBtnAttribute()
    {
        return $this->editBtn('admin.fangattr.edit').' '.$this->delBtn('admin.fangattr.destroy');
    }
}
