<?php

namespace App\Models;
use App\Observers\FangAttrObserver;

class Fangattr extends Base
{
    //获取修改icon字段输出
    public function getIconAttribute()
    {
        if(stristr($this->attributes['icon'],'http')){
            return $this->attributes['icon'];
        }
        return self::$host .'/' .ltrim($this->attributes['icon'],'/');
    }
    protected $appends=['actionBtn'];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(FangAttrObserver::class);
    }
    public function getactionBtnAttribute()
    {
        return $this->editBtn('admin.fangattr.edit').' '.$this->delBtn('admin.fangattr.destroy');
    }
}
